#include <bits/stdc++.h>
using namespace std;

const long long MOD = 1000000007;

void solve(long long K, long long D){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long K;
    scanf("%lld",&K);
    long long D;
    scanf("%lld",&D);
    solve(K, D);
    return 0;
}
