#include <bits/stdc++.h>
using namespace std;

const long long MOD = 1000000007;

void solve(long long H, long long W, std::vector<std::vector<std::string>> a){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long H;
    scanf("%lld",&H);
    long long W;
    scanf("%lld",&W);
    std::vector<std::vector<std::string>> a(H, std::vector<std::string>(1));
    for(int i = 0 ; i < H ; i++){
        for(int j = 0 ; j < 1 ; j++){
            std::cin >> a[i][j];
        }
    }
    solve(H, W, std::move(a));
    return 0;
}
