#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> w, std::vector<long long> s, std::vector<long long> v){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> w(N);
    std::vector<long long> s(N);
    std::vector<long long> v(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&w[i]);
        scanf("%lld",&s[i]);
        scanf("%lld",&v[i]);
    }
    solve(N, std::move(w), std::move(s), std::move(v));
    return 0;
}
