#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long M, std::vector<long long> l, std::vector<long long> r, std::vector<long long> a){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long M;
    scanf("%lld",&M);
    std::vector<long long> l(M);
    std::vector<long long> r(M);
    std::vector<long long> a(M);
    for(int i = 0 ; i < M ; i++){
        scanf("%lld",&l[i]);
        scanf("%lld",&r[i]);
        scanf("%lld",&a[i]);
    }
    solve(N, M, std::move(l), std::move(r), std::move(a));
    return 0;
}
